---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: nginxappsot
  namespace: fluxcdtutorial
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/biraderomkar/nginxAppSOT.git

