
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginxappsotkust
  namespace: fluxcdtutorial
spec:
  interval: 1m0s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: nginxappsot

